#!/bin/bash
#Note: No guarantee that this theme will be seen correctly at all screen resolutions available
#execute only from within the ubuntu-touch-splash folder!

sudo mkdir /usr/share/plymouth/themes/ubuntu-touch
clear
sudo rsync -aq --exclude=install-ubuntu-touch * /usr/share/plymouth/themes/ubuntu-touch/
clear
sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/ubuntu-touch/ubuntu-touch.plymouth 100
sudo update-alternatives --config default.plymouth  #here, choose the number of the theme you want to use then hit enter
sudo update-initramfs -u
echo
echo Installing plymouth-x11...   Redundant if already installed.
sudo apt-get install plymouth-x11
echo
echo Running 10-second test...
sudo plymouthd ; sudo plymouth --show-splash ; for ((I=0; I<10; I++)); do sleep 1 ; sudo plymouth --update=test$I ; done ; sudo plymouth --quit
clear
echo
echo If or when you want to restore the original Plymouth theme, 
echo    execute the script: ./update-plymouth 
echo 
echo If you want to test the theme without re-starting the machine,
echo    execute the script: ./test-plymouth
echo
echo If you want to test the theme after any modifications,
echo    execute the script: ./update-ubuntu-touch
echo
echo Scripts may be executed from the folder where ubuntu-touch.tar.gz was extracted,
echo    OR from /usr/share/plymouth/themes/ubuntu-touch.
echo
echo
read -p "Press ENTER to exit."
exit
