#!/bin/bash

if [ "$PWD" != "/lib/plymouth/themes/ubuntu-touch" ] ; then
sudo cp * /lib/plymouth/themes/ubuntu-touch/
clear
fi
sudo update-initramfs -u
echo
echo "Running 10-second test..."
sudo plymouthd ; sudo plymouth --show-splash ; for ((I=0; I<10; I++)); do sleep 1 ; sudo plymouth --update=test$I ; done ; sudo plymouth --quit
exit
